travis:
  secure:
    BINSTAR_TOKEN: eKKgeBf1wZ5uRmqX2liOMOrJVXyUYuW4u44ljuu5xh57Qz2BP4L6mH2hGa6kNNBBz2+sBkhVfwGLIvi1H/caUe+pjDYsdy0Nf3nAXBwAS+3bGLUBji7mDAonh4QEWzSpWItJWahbkufoehZJriPuBrLOnv7PVPRgH9JnGsYWOwVu9fucChk86XZlVvlzujbNeyYdBCCQrQ4qelvCAjmP/sFcV9ZzGV7enm/wuR2uP3BVMlK8sLQ6sVSZzkrJqo3ENb6rbvOQjD08zv4sar0nUmr3EiytQ1fOB6ymoYRgmHajX8J/Pxz93r3Lr3E4dVG5aSAhJdJPZ7zaGPKJgMZ9cF6kppSbksVc8TVWvhOe7nCRzxHKZAu6aG1AcIrjV9OTiMWjcf8hByPeMnaXbTH3+DLk9tDjKX2o8YNzfDVP7xyurI19ZY1TSgsE3kSFP6r41MAWW7yT2JM/uNawYk32s+S9ONEaA2D7jCKmdU7oRrFtXA1iJny11PusXM81k516EatMMU71KIa1y6CDRm3tXRGxHOHa2WAy1TQMQwRWXHVdzA3ZAn5h3aZ+WHTQ1lBw3cVP6bqVPgKHzAdW8ISjNOn++2eESwlWxRl3KJgLdcVyDVRiqgr6DHVnQJ9R/jxBm6u93w738+gGQPAypFc2Bv+fborAilks9Ig78PuEuPc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
