travis:
  secure:
    BINSTAR_TOKEN: DlPrsdg69gQRgtnHV1lH4sxQnXJRWybkFZIu4gNSiGl6AeFNANjwUBjEDm9MqdTDkoOJaaftg3HvCHdNnPts5T9Inku6R4NwVVswmQk1IZMx4lsle3f00TEeGBNuXehv2c3vAM6vPhB1mxgM8G4vhLfDftfY5xQb2DfDFkJ5VFhmKow9Kp4JigXMR8vjOTedt7Td8vqafMHcAY0BdZ2XPcE1gHaCe0JrY/Wa5fkTQOU0X8mIINsAZbEzM/JnYKIXSdW4MjLPOoqb83sAzXLOQxYFbSE3lew8uSIZK8AE2RRCU1MHCcZbr03YQJvRvVa5GIvrhyOEPqKCaFiIRMY2Fa1r0QJxCE78XF/pSEHCQ9dYb+l055GEZ8dV+EsdniWMXhscBDCkAZWsO0YXrBmSr0X9Sl+Vp/xnfgQZsWs9v+TgXW1vCZI678W0Om1WiHfyhO74Xvo/7POQUw/ePXz4BfXdOpWN74TvE4tYrRtPDCG0qHHxp5ZNi2i5jI36EbwMn7mo1WOg/K//NVj7bOzA6gpkHuNuydliSV3aR5nsVxCH03o0ERzwD7CYOnXGf8jXUKthFNwkQrhYzJWmHQwyq0c7bRJGDr1UP5Xab/yERwpLmShm07F2NJC65TicELgqLtt4+w/rv5c26eruTdTQsW5S6UOxqD3bezvuvSbHuEY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
