travis:
  secure:
    BINSTAR_TOKEN: h4s3ra6hftPi1z7g3sPyBo5lsOSu72jpVaJoGEJGIf2M+3WBO0K6zq3oROPkq7IgdBNc5gmYo7VKcF9WLmpGwuRaf1Z1bTV/0d5hvrOV7a6tH9gt1ON5a/lZlw5MRx+YEyzL/3Os1/hT8EQ7uLflEI+c4ZyROmP5qeUcuC6CEyZ6MCbCPJTzKnVgvNnUdpQnNRuaOzBlTrql0IEm9TF4I6uINqGzIHfnWS0/JeiYuJSSZX44BIxpA52mwqzks3sKWRdl2w17BfK6hR7VnkdpzRY8o6tKB5Sb8p8GqCf568RoVHhJAYdiIKhx+LHAG324EhhAHWLRRbQZzH85CeImBr69SxM5U4I3PASewHNj8OjejEp4Y4XfrVZGs2hOuPRGZYucxrFiVHpSnxiFYP34/iovFp8f6IFlsxYC8ZzMSc1sc1iHFVeMFglMCktb4+tPtAiPisATHsUTjknI1VFevyZ+3CuJBw6p5YW+/WldylQ0OeZK7dVRaeEiFpTRdee6sDiI75stCAWBdTAOgJQa8R4utDV8JR0qN3bARo2Z3gbj/jdWWo5jDgZPUZ/Ffrg2TXHWm9TQw8NZrBupqTrAo1XhIYuM8kMI6SB2fLZ0mXDVCrA9Exiiur5JIOrzzgnqn9fkdChVyKXoMGRd9hwDPPePGhSpPWCgON9SeORVYBE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
