travis:
  secure:
    BINSTAR_TOKEN: J0fVoaI1nJkaIBLBmVuDHk50DcOikNsI0VheLOQuOlSSzerhIOVFd++Ea2r3T9MNPsQJ0KPzuu8YWl1V/DXws0JEsDnCZKH4m6sAPVyqrF6TQtT4tGg59JmExAjKQuEByjoblAUrJ37ZikCXjFJT2Gc/ZOPTo4cdk0DsZ5QEcvYq+ta4Lm0Hn2DuOMYEzTvAckCZ4k6XjwLQAzJbBgxXbDTq+wQ1kWqJIOVlKMw0RP1XlXP64xHAMo8GSfagewM3jfje/RcdpX1xSP1moH2X6HjUCBrCpGfcH0n3AOrQFFsgGpnqfEpJntvvOtp0Bq6P2HvWjcRhteJFnSNzGoNeoD8LitIUB3CNpAJJqSSdqPnvN41a4OMfb/6yPQU6QJMI5Jw73bxDYpW9g6AZ7V6w6PAlz6reNb3WjET5bNd7IwtQunEnUXjPrQWAJSOCOK4NEqoR/eUAyYm9w+Ps9gNqEzSqrZA6EuNx5MLPudZ41iIWC6rzmXfA0O7Vh0Ch3Fl1I4T4GvinG2KgZilf/af3IPP4MwuTRm/NpeulgP5P+bOKTz/9V3X58qANvwyHA45fbRdvE7X7Jk6gkUlx0MmK+vi69lRaIFUszWxnnKk1hMln8uCwFj+P2bz0NyLNxpLNt5EVXw0AsUgAbb6wbRIwpdkwTY0E4XmMDDaz+Y7F8g8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
